version: '3.9'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: YoGa
    # volumes:
    #   - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
  client:
    build:
      context: ./client
    volumes:
      - staticbuild:/app/out
 
  nginx:
    build:
      context: ./nginx
    volumes:
      - staticbuild:/app/public
    ports:
      - “8080:80”
 
  networks:
    dev:
      driver: bridge
 
  volumes:
    staticbuild:
    
