version: "3.8"
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=970bc93e3a88d5e48e511be31ae86f7f6684a9c8774d2aaa206ac046d692eb6b72b25098dbf8394e55ba65fe46b0ebfbace8
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - mynetwork
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "8070:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: SuperSecret
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: "True"
      PGADMIN_CONFIG_LOGIN_BANNER: "Authorised users only!"
      PGADMIN_CONFIG_CONSOLE_LOG_LEVEL: "10"
    container_name: pgadmin4\
    networks:
      - mynetwork
networks:
  mynetwork:
    driver: bridge
volumes:
  db:
    driver: local
